### ISSUE TITLE
:rotating_light: Fix look function

### ISSUE THREAD

**Issue by Peralban** [Peralban/Zappy#57]
:ambulance: **Describe the bug**
Bug on display of look

**To Reproduce**
1. Launch the program
2. Connect a client
3. Look command
4. Sometime it will be have a problem on display

**Screenshots**
![image](https://github.com/Peralban/Zappy/assets/114707036/68613c3a-ed21-4387-ad7c-4313b0d17cfb)

**Comment by landryarki** [comment]
there is a problem about the direction of looking
![image](https://github.com/Peralban/Zappy/assets/114699649/30384f96-03c5-4972-b864-17eeda2a2b8a)
