### ISSUE TITLE
:nerd_face: Create Admin Function

### ISSUE THREAD

**Issue by Peralban** [Peralban/Zappy#95]
# :clipboard: What's needed
- [x] Create Admin client role.
- [x] Create the archi to welcome the future admin function
- [x] Create level functions - down function */levelup #n* // */leveldown #n* // *level #n %l*
- [x] Create set inventory functions */setinventory 0 1 2 3 4 5 6*
- [x] Create tp functions */tp #n w h*
- [x] create time functions */pause* // */set_freq t* // */tick [s|t]*

**Comment by landryarki** [comment]
i noticed some edge case (tp out of the bound for exemple) that crash the server. we should take a closer look to each functions
